# Generated by Django 5.0.4 on 2024-04-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('screenshot', models.ImageField(upload_to='screenshots/')),
                ('ip_address', models.CharField(max_length=50)),
                ('source_url', models.URLField()),
                ('destination_url', models.URLField()),
                ('asn_information', models.CharField(max_length=100)),
                ('ssl_certificate_details', models.TextField()),
                ('page_source', models.TextField()),
                ('natural_language_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
