# Generated by Django 5.0.4 on 2024-04-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_scanner_app', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='scanresult',
        #     name='created_at',
        # ),
        migrations.AlterField(
            model_name='scanresult',
            name='screenshot',
            field=models.ImageField(upload_to='media/screenshots/'),
        ),
    ]
