# Generated by Django 5.0.4 on 2024-04-07 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_scanner_app', '0002_remove_scanresult_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanresult',
            name='created_at',
        ),
    ]
