# Generated by Django 5.0.4 on 2024-04-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_scanner_app', '0003_remove_scanresult_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='screenshot',
            field=models.ImageField(upload_to='screenshots/'),
        ),
    ]
