# Generated by Django 5.0.4 on 2024-04-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_scanner_app', '0004_alter_scanresult_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='extracted_information',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
